# config/packages/messenger.yaml
framework:
    messenger:
        # Enable this to send emails in background
        transports:
            async:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
